//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankServiceClientApp.BankService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BankService.services.ramesh/")]
    public partial class InvalidInputValues : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(account))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BankService.services.ramesh/")]
    public abstract partial class baseAccount : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private double balanceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
                this.RaisePropertyChanged("balance");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BankService.services.ramesh/")]
    public partial class account : baseAccount {
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string phoneNoField;
        
        private string addressField;
        
        private string nICField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("firstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("lastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string phoneNo {
            get {
                return this.phoneNoField;
            }
            set {
                this.phoneNoField = value;
                this.RaisePropertyChanged("phoneNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string NIC {
            get {
                return this.nICField;
            }
            set {
                this.nICField = value;
                this.RaisePropertyChanged("NIC");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BankService.services.ramesh/")]
    public partial class createAccountRes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private baseAccount accField;
        
        private string passCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public baseAccount acc {
            get {
                return this.accField;
            }
            set {
                this.accField = value;
                this.RaisePropertyChanged("acc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string passCode {
            get {
                return this.passCodeField;
            }
            set {
                this.passCodeField = value;
                this.RaisePropertyChanged("passCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BankService.services.ramesh/")]
    public partial class CantFindTheAccount : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BankService.services.ramesh/")]
    public partial class InsufficientBalance : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://BankService.services.ramesh/", ConfigurationName="BankService.BankService")]
    public interface BankService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://BankService.services.ramesh/BankService/createAccountRequest", ReplyAction="http://BankService.services.ramesh/BankService/createAccountResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BankServiceClientApp.BankService.InvalidInputValues), Action="http://BankService.services.ramesh/BankService/createAccount/Fault/InvalidInputVa" +
            "lues", Name="InvalidInputValues")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BankServiceClientApp.BankService.createAccountResponse createAccount(BankServiceClientApp.BankService.createAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://BankService.services.ramesh/BankService/createAccountRequest", ReplyAction="http://BankService.services.ramesh/BankService/createAccountResponse")]
        System.Threading.Tasks.Task<BankServiceClientApp.BankService.createAccountResponse> createAccountAsync(BankServiceClientApp.BankService.createAccountRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://BankService.services.ramesh/BankService/withdrawMoneyRequest", ReplyAction="http://BankService.services.ramesh/BankService/withdrawMoneyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BankServiceClientApp.BankService.CantFindTheAccount), Action="http://BankService.services.ramesh/BankService/withdrawMoney/Fault/CantFindTheAcc" +
            "ount", Name="CantFindTheAccount")]
        [System.ServiceModel.FaultContractAttribute(typeof(BankServiceClientApp.BankService.InvalidInputValues), Action="http://BankService.services.ramesh/BankService/withdrawMoney/Fault/InvalidInputVa" +
            "lues", Name="InvalidInputValues")]
        [System.ServiceModel.FaultContractAttribute(typeof(BankServiceClientApp.BankService.InsufficientBalance), Action="http://BankService.services.ramesh/BankService/withdrawMoney/Fault/InsufficientBa" +
            "lance", Name="InsufficientBalance")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BankServiceClientApp.BankService.withdrawMoneyResponse withdrawMoney(BankServiceClientApp.BankService.withdrawMoneyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://BankService.services.ramesh/BankService/withdrawMoneyRequest", ReplyAction="http://BankService.services.ramesh/BankService/withdrawMoneyResponse")]
        System.Threading.Tasks.Task<BankServiceClientApp.BankService.withdrawMoneyResponse> withdrawMoneyAsync(BankServiceClientApp.BankService.withdrawMoneyRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://BankService.services.ramesh/BankService/transferMoneyRequest", ReplyAction="http://BankService.services.ramesh/BankService/transferMoneyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BankServiceClientApp.BankService.CantFindTheAccount), Action="http://BankService.services.ramesh/BankService/transferMoney/Fault/CantFindTheAcc" +
            "ount", Name="CantFindTheAccount")]
        [System.ServiceModel.FaultContractAttribute(typeof(BankServiceClientApp.BankService.InvalidInputValues), Action="http://BankService.services.ramesh/BankService/transferMoney/Fault/InvalidInputVa" +
            "lues", Name="InvalidInputValues")]
        [System.ServiceModel.FaultContractAttribute(typeof(BankServiceClientApp.BankService.InsufficientBalance), Action="http://BankService.services.ramesh/BankService/transferMoney/Fault/InsufficientBa" +
            "lance", Name="InsufficientBalance")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BankServiceClientApp.BankService.transferMoneyResponse transferMoney(BankServiceClientApp.BankService.transferMoneyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://BankService.services.ramesh/BankService/transferMoneyRequest", ReplyAction="http://BankService.services.ramesh/BankService/transferMoneyResponse")]
        System.Threading.Tasks.Task<BankServiceClientApp.BankService.transferMoneyResponse> transferMoneyAsync(BankServiceClientApp.BankService.transferMoneyRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://BankService.services.ramesh/BankService/getAccountsRequest", ReplyAction="http://BankService.services.ramesh/BankService/getAccountsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BankServiceClientApp.BankService.getAccountsResponse getAccounts(BankServiceClientApp.BankService.getAccountsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://BankService.services.ramesh/BankService/getAccountsRequest", ReplyAction="http://BankService.services.ramesh/BankService/getAccountsResponse")]
        System.Threading.Tasks.Task<BankServiceClientApp.BankService.getAccountsResponse> getAccountsAsync(BankServiceClientApp.BankService.getAccountsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://BankService.services.ramesh/BankService/depositMoneyRequest", ReplyAction="http://BankService.services.ramesh/BankService/depositMoneyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BankServiceClientApp.BankService.CantFindTheAccount), Action="http://BankService.services.ramesh/BankService/depositMoney/Fault/CantFindTheAcco" +
            "unt", Name="CantFindTheAccount")]
        [System.ServiceModel.FaultContractAttribute(typeof(BankServiceClientApp.BankService.InvalidInputValues), Action="http://BankService.services.ramesh/BankService/depositMoney/Fault/InvalidInputVal" +
            "ues", Name="InvalidInputValues")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BankServiceClientApp.BankService.depositMoneyResponse depositMoney(BankServiceClientApp.BankService.depositMoneyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://BankService.services.ramesh/BankService/depositMoneyRequest", ReplyAction="http://BankService.services.ramesh/BankService/depositMoneyResponse")]
        System.Threading.Tasks.Task<BankServiceClientApp.BankService.depositMoneyResponse> depositMoneyAsync(BankServiceClientApp.BankService.depositMoneyRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://BankService.services.ramesh/BankService/checkAccountBalanceRequest", ReplyAction="http://BankService.services.ramesh/BankService/checkAccountBalanceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BankServiceClientApp.BankService.CantFindTheAccount), Action="http://BankService.services.ramesh/BankService/checkAccountBalance/Fault/CantFind" +
            "TheAccount", Name="CantFindTheAccount")]
        [System.ServiceModel.FaultContractAttribute(typeof(BankServiceClientApp.BankService.InvalidInputValues), Action="http://BankService.services.ramesh/BankService/checkAccountBalance/Fault/InvalidI" +
            "nputValues", Name="InvalidInputValues")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BankServiceClientApp.BankService.checkAccountBalanceResponse checkAccountBalance(BankServiceClientApp.BankService.checkAccountBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://BankService.services.ramesh/BankService/checkAccountBalanceRequest", ReplyAction="http://BankService.services.ramesh/BankService/checkAccountBalanceResponse")]
        System.Threading.Tasks.Task<BankServiceClientApp.BankService.checkAccountBalanceResponse> checkAccountBalanceAsync(BankServiceClientApp.BankService.checkAccountBalanceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createAccount", WrapperNamespace="http://BankService.services.ramesh/", IsWrapped=true)]
    public partial class createAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankService.services.ramesh/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string firstName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankService.services.ramesh/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lastName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankService.services.ramesh/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string phoneNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankService.services.ramesh/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string address;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankService.services.ramesh/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NIC;
        
        public createAccountRequest() {
        }
        
        public createAccountRequest(string firstName, string lastName, string phoneNo, string address, string NIC) {
            this.firstName = firstName;
            this.lastName = lastName;
            this.phoneNo = phoneNo;
            this.address = address;
            this.NIC = NIC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createAccountResponse", WrapperNamespace="http://BankService.services.ramesh/", IsWrapped=true)]
    public partial class createAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankService.services.ramesh/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BankServiceClientApp.BankService.createAccountRes @return;
        
        public createAccountResponse() {
        }
        
        public createAccountResponse(BankServiceClientApp.BankService.createAccountRes @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="withdrawMoney", WrapperNamespace="http://BankService.services.ramesh/", IsWrapped=true)]
    public partial class withdrawMoneyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankService.services.ramesh/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string accountId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankService.services.ramesh/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankService.services.ramesh/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double withdrawAmount;
        
        public withdrawMoneyRequest() {
        }
        
        public withdrawMoneyRequest(string accountId, string passCode, double withdrawAmount) {
            this.accountId = accountId;
            this.passCode = passCode;
            this.withdrawAmount = withdrawAmount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="withdrawMoneyResponse", WrapperNamespace="http://BankService.services.ramesh/", IsWrapped=true)]
    public partial class withdrawMoneyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankService.services.ramesh/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double @return;
        
        public withdrawMoneyResponse() {
        }
        
        public withdrawMoneyResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="transferMoney", WrapperNamespace="http://BankService.services.ramesh/", IsWrapped=true)]
    public partial class transferMoneyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankService.services.ramesh/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string transferAccountId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankService.services.ramesh/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string receiverAccountId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankService.services.ramesh/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankService.services.ramesh/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double transferAmount;
        
        public transferMoneyRequest() {
        }
        
        public transferMoneyRequest(string transferAccountId, string receiverAccountId, string passCode, double transferAmount) {
            this.transferAccountId = transferAccountId;
            this.receiverAccountId = receiverAccountId;
            this.passCode = passCode;
            this.transferAmount = transferAmount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="transferMoneyResponse", WrapperNamespace="http://BankService.services.ramesh/", IsWrapped=true)]
    public partial class transferMoneyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankService.services.ramesh/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double @return;
        
        public transferMoneyResponse() {
        }
        
        public transferMoneyResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAccounts", WrapperNamespace="http://BankService.services.ramesh/", IsWrapped=true)]
    public partial class getAccountsRequest {
        
        public getAccountsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAccountsResponse", WrapperNamespace="http://BankService.services.ramesh/", IsWrapped=true)]
    public partial class getAccountsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankService.services.ramesh/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BankServiceClientApp.BankService.baseAccount[] @return;
        
        public getAccountsResponse() {
        }
        
        public getAccountsResponse(BankServiceClientApp.BankService.baseAccount[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="depositMoney", WrapperNamespace="http://BankService.services.ramesh/", IsWrapped=true)]
    public partial class depositMoneyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankService.services.ramesh/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string accountId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankService.services.ramesh/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankService.services.ramesh/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double depositAmount;
        
        public depositMoneyRequest() {
        }
        
        public depositMoneyRequest(string accountId, string passCode, double depositAmount) {
            this.accountId = accountId;
            this.passCode = passCode;
            this.depositAmount = depositAmount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="depositMoneyResponse", WrapperNamespace="http://BankService.services.ramesh/", IsWrapped=true)]
    public partial class depositMoneyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankService.services.ramesh/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double @return;
        
        public depositMoneyResponse() {
        }
        
        public depositMoneyResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkAccountBalance", WrapperNamespace="http://BankService.services.ramesh/", IsWrapped=true)]
    public partial class checkAccountBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankService.services.ramesh/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string accountId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankService.services.ramesh/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passCode;
        
        public checkAccountBalanceRequest() {
        }
        
        public checkAccountBalanceRequest(string accountId, string passCode) {
            this.accountId = accountId;
            this.passCode = passCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkAccountBalanceResponse", WrapperNamespace="http://BankService.services.ramesh/", IsWrapped=true)]
    public partial class checkAccountBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BankService.services.ramesh/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double @return;
        
        public checkAccountBalanceResponse() {
        }
        
        public checkAccountBalanceResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BankServiceChannel : BankServiceClientApp.BankService.BankService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankServiceClient : System.ServiceModel.ClientBase<BankServiceClientApp.BankService.BankService>, BankServiceClientApp.BankService.BankService {
        
        public BankServiceClient() {
        }
        
        public BankServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankServiceClientApp.BankService.createAccountResponse BankServiceClientApp.BankService.BankService.createAccount(BankServiceClientApp.BankService.createAccountRequest request) {
            return base.Channel.createAccount(request);
        }
        
        public BankServiceClientApp.BankService.createAccountRes createAccount(string firstName, string lastName, string phoneNo, string address, string NIC) {
            BankServiceClientApp.BankService.createAccountRequest inValue = new BankServiceClientApp.BankService.createAccountRequest();
            inValue.firstName = firstName;
            inValue.lastName = lastName;
            inValue.phoneNo = phoneNo;
            inValue.address = address;
            inValue.NIC = NIC;
            BankServiceClientApp.BankService.createAccountResponse retVal = ((BankServiceClientApp.BankService.BankService)(this)).createAccount(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankServiceClientApp.BankService.createAccountResponse> BankServiceClientApp.BankService.BankService.createAccountAsync(BankServiceClientApp.BankService.createAccountRequest request) {
            return base.Channel.createAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankServiceClientApp.BankService.createAccountResponse> createAccountAsync(string firstName, string lastName, string phoneNo, string address, string NIC) {
            BankServiceClientApp.BankService.createAccountRequest inValue = new BankServiceClientApp.BankService.createAccountRequest();
            inValue.firstName = firstName;
            inValue.lastName = lastName;
            inValue.phoneNo = phoneNo;
            inValue.address = address;
            inValue.NIC = NIC;
            return ((BankServiceClientApp.BankService.BankService)(this)).createAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankServiceClientApp.BankService.withdrawMoneyResponse BankServiceClientApp.BankService.BankService.withdrawMoney(BankServiceClientApp.BankService.withdrawMoneyRequest request) {
            return base.Channel.withdrawMoney(request);
        }
        
        public double withdrawMoney(string accountId, string passCode, double withdrawAmount) {
            BankServiceClientApp.BankService.withdrawMoneyRequest inValue = new BankServiceClientApp.BankService.withdrawMoneyRequest();
            inValue.accountId = accountId;
            inValue.passCode = passCode;
            inValue.withdrawAmount = withdrawAmount;
            BankServiceClientApp.BankService.withdrawMoneyResponse retVal = ((BankServiceClientApp.BankService.BankService)(this)).withdrawMoney(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankServiceClientApp.BankService.withdrawMoneyResponse> BankServiceClientApp.BankService.BankService.withdrawMoneyAsync(BankServiceClientApp.BankService.withdrawMoneyRequest request) {
            return base.Channel.withdrawMoneyAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankServiceClientApp.BankService.withdrawMoneyResponse> withdrawMoneyAsync(string accountId, string passCode, double withdrawAmount) {
            BankServiceClientApp.BankService.withdrawMoneyRequest inValue = new BankServiceClientApp.BankService.withdrawMoneyRequest();
            inValue.accountId = accountId;
            inValue.passCode = passCode;
            inValue.withdrawAmount = withdrawAmount;
            return ((BankServiceClientApp.BankService.BankService)(this)).withdrawMoneyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankServiceClientApp.BankService.transferMoneyResponse BankServiceClientApp.BankService.BankService.transferMoney(BankServiceClientApp.BankService.transferMoneyRequest request) {
            return base.Channel.transferMoney(request);
        }
        
        public double transferMoney(string transferAccountId, string receiverAccountId, string passCode, double transferAmount) {
            BankServiceClientApp.BankService.transferMoneyRequest inValue = new BankServiceClientApp.BankService.transferMoneyRequest();
            inValue.transferAccountId = transferAccountId;
            inValue.receiverAccountId = receiverAccountId;
            inValue.passCode = passCode;
            inValue.transferAmount = transferAmount;
            BankServiceClientApp.BankService.transferMoneyResponse retVal = ((BankServiceClientApp.BankService.BankService)(this)).transferMoney(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankServiceClientApp.BankService.transferMoneyResponse> BankServiceClientApp.BankService.BankService.transferMoneyAsync(BankServiceClientApp.BankService.transferMoneyRequest request) {
            return base.Channel.transferMoneyAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankServiceClientApp.BankService.transferMoneyResponse> transferMoneyAsync(string transferAccountId, string receiverAccountId, string passCode, double transferAmount) {
            BankServiceClientApp.BankService.transferMoneyRequest inValue = new BankServiceClientApp.BankService.transferMoneyRequest();
            inValue.transferAccountId = transferAccountId;
            inValue.receiverAccountId = receiverAccountId;
            inValue.passCode = passCode;
            inValue.transferAmount = transferAmount;
            return ((BankServiceClientApp.BankService.BankService)(this)).transferMoneyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankServiceClientApp.BankService.getAccountsResponse BankServiceClientApp.BankService.BankService.getAccounts(BankServiceClientApp.BankService.getAccountsRequest request) {
            return base.Channel.getAccounts(request);
        }
        
        public BankServiceClientApp.BankService.baseAccount[] getAccounts() {
            BankServiceClientApp.BankService.getAccountsRequest inValue = new BankServiceClientApp.BankService.getAccountsRequest();
            BankServiceClientApp.BankService.getAccountsResponse retVal = ((BankServiceClientApp.BankService.BankService)(this)).getAccounts(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankServiceClientApp.BankService.getAccountsResponse> BankServiceClientApp.BankService.BankService.getAccountsAsync(BankServiceClientApp.BankService.getAccountsRequest request) {
            return base.Channel.getAccountsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankServiceClientApp.BankService.getAccountsResponse> getAccountsAsync() {
            BankServiceClientApp.BankService.getAccountsRequest inValue = new BankServiceClientApp.BankService.getAccountsRequest();
            return ((BankServiceClientApp.BankService.BankService)(this)).getAccountsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankServiceClientApp.BankService.depositMoneyResponse BankServiceClientApp.BankService.BankService.depositMoney(BankServiceClientApp.BankService.depositMoneyRequest request) {
            return base.Channel.depositMoney(request);
        }
        
        public double depositMoney(string accountId, string passCode, double depositAmount) {
            BankServiceClientApp.BankService.depositMoneyRequest inValue = new BankServiceClientApp.BankService.depositMoneyRequest();
            inValue.accountId = accountId;
            inValue.passCode = passCode;
            inValue.depositAmount = depositAmount;
            BankServiceClientApp.BankService.depositMoneyResponse retVal = ((BankServiceClientApp.BankService.BankService)(this)).depositMoney(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankServiceClientApp.BankService.depositMoneyResponse> BankServiceClientApp.BankService.BankService.depositMoneyAsync(BankServiceClientApp.BankService.depositMoneyRequest request) {
            return base.Channel.depositMoneyAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankServiceClientApp.BankService.depositMoneyResponse> depositMoneyAsync(string accountId, string passCode, double depositAmount) {
            BankServiceClientApp.BankService.depositMoneyRequest inValue = new BankServiceClientApp.BankService.depositMoneyRequest();
            inValue.accountId = accountId;
            inValue.passCode = passCode;
            inValue.depositAmount = depositAmount;
            return ((BankServiceClientApp.BankService.BankService)(this)).depositMoneyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankServiceClientApp.BankService.checkAccountBalanceResponse BankServiceClientApp.BankService.BankService.checkAccountBalance(BankServiceClientApp.BankService.checkAccountBalanceRequest request) {
            return base.Channel.checkAccountBalance(request);
        }
        
        public double checkAccountBalance(string accountId, string passCode) {
            BankServiceClientApp.BankService.checkAccountBalanceRequest inValue = new BankServiceClientApp.BankService.checkAccountBalanceRequest();
            inValue.accountId = accountId;
            inValue.passCode = passCode;
            BankServiceClientApp.BankService.checkAccountBalanceResponse retVal = ((BankServiceClientApp.BankService.BankService)(this)).checkAccountBalance(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankServiceClientApp.BankService.checkAccountBalanceResponse> BankServiceClientApp.BankService.BankService.checkAccountBalanceAsync(BankServiceClientApp.BankService.checkAccountBalanceRequest request) {
            return base.Channel.checkAccountBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankServiceClientApp.BankService.checkAccountBalanceResponse> checkAccountBalanceAsync(string accountId, string passCode) {
            BankServiceClientApp.BankService.checkAccountBalanceRequest inValue = new BankServiceClientApp.BankService.checkAccountBalanceRequest();
            inValue.accountId = accountId;
            inValue.passCode = passCode;
            return ((BankServiceClientApp.BankService.BankService)(this)).checkAccountBalanceAsync(inValue);
        }
    }
}
